name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Change permissions
      - name: Set Gradlew Permissions
        run: |
          cd demo
          chmod +x gradlew

      # Change directory to demo and build the Kotlin project
      - name: Build Kotlin project
        run: |
          cd demo
          ./gradlew clean build --stacktrace --info

      # Change directory to demo and build the Docker image for the Kotlin backend
      - name: Build Kotlin Docker image
        run: |
          cd demo
          docker build . --file Dockerfile --tag kotlin-app:latest

      # Log into Docker Hub (using secrets to authenticate)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Push the Docker image to Docker Hub (replace 'my-image-name' with your repo/image name)
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.USERNAME }}/kotlin-app:latest

      # Install dependencies for Next.js app (inside the 'front-end' folder)
      - name: Install dependencies for Next.js
        working-directory: ./front-end
        run: |
          npm install

      # Build Next.js application
      - name: Build Next.js app
        working-directory: ./front-end
        run: |
          npm run build
